name: Hello CI

on:
  push:

jobs:
  job-a:
    runs-on: ubuntu-latest

    steps:
      - name: Job A step
        run: exit 1

  job-b:
    needs: job-a
    runs-on: ubuntu-latest

    steps:
      - name: Job B step
        run: echo "Hello from Job B"
