name: Hello CI

on:
  push:

jobs:
  job-a:
    runs-on: ubuntu-latest

    steps:
      - name: Job A step
        run: echo "Hello from Job A"

  job-b:
    runs-on: ubuntu-latest

    steps:
      - name: Job B step
        run: echo "Hello from Job B"
